package database

import (
	"os"
	"time"

	"github.com/gofiber/fiber/v3/log"
	go_ora "github.com/sijms/go-ora/v2"
	"github.com/jmoiron/sqlx"
	"golang.project.structure/config"
)

var (
	OraDB *sqlx.DB
)

func Initialize() error {
	conf := config.LoadConfig()

	conStr := go_ora.BuildUrl(
		conf.DBHost,
		conf.DBPort,
		conf.DBName,
		conf.DBUser,
		conf.DBPassword,
		nil)

	db, err := sqlx.Open("oracle", conStr)
	if err != nil {
		return err
	}

	err = db.Ping()
	if err != nil {
		return err
	}

	db.SetMaxOpenConns(10)
	db.SetMaxIdleConns(5)
	db.SetConnMaxIdleTime(15 * time.Minute)

	OraDB = db

	log.Info("Oracle DB connection established")

	// Only create table if AUTO_CREATE_TABLES is enabled
	autoCreate := os.Getenv("AUTO_CREATE_TABLES")
	if autoCreate == "true" || autoCreate == "1" {
		// Check if users table exists and create if it doesn't
		err = ensureUsersTableExists()
		if err != nil {
			log.Errorf("Failed to ensure users table exists: %v", err)
			// Don't return error, just log it - let the app continue
			log.Warn("Continuing without auto-creating tables. Please create them manually.")
		}
	} else {
		log.Info("Auto table creation disabled. Ensure tables exist manually.")
	}

	return nil
}
// ensureUsersTableExists checks if the users table exists and creates it if it doesn't
func ensureUsersTableExists() error {
	// Check if table exists
	var count int
	checkQuery := `
		SELECT COUNT(*) 
		FROM user_tables 
		WHERE table_name = 'USERS'
	`
	
	err := OraDB.Get(&count, checkQuery)
	if err != nil {
		log.Errorf("Error checking if users table exists: %v", err)
		return err
	}

	if count == 0 {
		log.Info("Users table does not exist. Creating...")
		err = createUsersTable()
		if err != nil {
			return err
		}
		log.Info("Users table created successfully")
	} else {
		log.Info("Users table already exists")
	}

	return nil
}

// createUsersTable creates the users table with sample data
func createUsersTable() error {
	// Create table in SCOTT's own schema (no tablespace specified)
	createTableQuery := `
		CREATE TABLE users (
			ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			NAME VARCHAR2(100) NOT NULL,
			EMAIL VARCHAR2(255) NOT NULL UNIQUE,
			PHONE VARCHAR2(20),
			STATUS VARCHAR2(20) DEFAULT 'active' CHECK (STATUS IN ('active', 'inactive', 'suspended')),
			CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	`

	_, err := OraDB.Exec(createTableQuery)
	if err != nil {
		log.Errorf("Error creating users table: %v", err)
		return err
	}

	// Create indexes (with error handling for existing indexes)
	createIndexQueries := []string{
		"CREATE INDEX idx_users_email ON users(EMAIL)",
		"CREATE INDEX idx_users_status ON users(STATUS)",
	}

	for _, query := range createIndexQueries {
		_, err := OraDB.Exec(query)
		if err != nil {
			// Check if it's just because index already exists
			if !isIndexAlreadyExistsError(err) {
				log.Warnf("Warning: Failed to create index: %v", err)
			}
			// Continue even if index creation fails
		}
	}

	// Insert sample data only if table is empty
	var userCount int
	countQuery := "SELECT COUNT(*) FROM users"
	err = OraDB.Get(&userCount, countQuery)
	if err != nil {
		log.Warnf("Warning: Could not check user count: %v", err)
		return nil // Don't fail the entire initialization
	}

	if userCount > 0 {
		log.Info("Users table already contains data, skipping sample data insertion")
		return nil
	}

	// Insert sample data
	sampleUsers := []struct {
		Name   string
		Email  string
		Phone  string
		Status string
	}{
		{"John Doe", "john.doe@example.com", "+1234567890", "active"},
		{"Jane Smith", "jane.smith@example.com", "+0987654321", "active"},
		{"Bob Johnson", "bob.johnson@example.com", "+1122334455", "active"},
	}

	insertQuery := `
		INSERT INTO users (NAME, EMAIL, PHONE, STATUS) 
		VALUES (:1, :2, :3, :4)
	`

	successCount := 0
	for _, user := range sampleUsers {
		_, err := OraDB.Exec(insertQuery, user.Name, user.Email, user.Phone, user.Status)
		if err != nil {
			log.Warnf("Warning: Failed to insert sample user %s: %v", user.Email, err)
			// Continue even if sample data insertion fails
		} else {
			successCount++
		}
	}

	if successCount > 0 {
		log.Infof("Successfully inserted %d sample users", successCount)
	} else {
		log.Warn("No sample users were inserted due to errors")
	}
	
	return nil
}

// isIndexAlreadyExistsError checks if the error is due to index already existing
func isIndexAlreadyExistsError(err error) bool {
	if err == nil {
		return false
	}
	errStr := err.Error()
	return contains(errStr, "ORA-01408") || contains(errStr, "already indexed")
}

// contains checks if a string contains a substring (helper function)
func contains(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(substr) == 0 || 
		(len(s) > len(substr) && (s[:len(substr)] == substr || s[len(s)-len(substr):] == substr || 
		indexOfSubstring(s, substr) >= 0)))
}

// indexOfSubstring finds the index of substring in string
func indexOfSubstring(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}