-- Create Users Table
-- This script creates the users table for the Go Fiber API

-- Drop table if exists (optional - uncomment if you want to recreate)
-- DROP TABLE users;

-- Create users table
CREATE TABLE users (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PHONE VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'active' CHECK (STATUS IN ('active', 'inactive', 'suspended')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on email for faster lookups
CREATE INDEX idx_users_email ON users(EMAIL);

-- Create index on status for filtering
CREATE INDEX idx_users_status ON users(STATUS);

-- Insert sample data (optional)
INSERT INTO users (NAME, EMAIL, PHONE, STATUS) VALUES 
('John Doe', 'john.doe@example.com', '+1234567890', 'active');

INSERT INTO users (NAME, EMAIL, PHONE, STATUS) VALUES 
('Jane Smith', 'jane.smith@example.com', '+0987654321', 'active');

INSERT INTO users (NAME, EMAIL, PHONE, STATUS) VALUES 
('Bob Johnson', 'bob.johnson@example.com', '+1122334455', 'active');

-- Commit the changes
COMMIT;

-- Verify the table was created
SELECT COUNT(*) as user_count FROM users;
SELECT * FROM users ORDER BY CREATED_AT DESC;