-- Oracle Database Setup Script for Go Fiber API
-- Run this script as SCOTT user (not SYSTEM)

-- Connect as SCOTT user
-- sqlplus scott/tiger@your_database

-- 1. Drop existing table if it exists (optional)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- 2. Create the users table in SCOTT's schema
CREATE TABLE users (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PHONE VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'active' CHECK (STATUS IN ('active', 'inactive', 'suspended')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create indexes
CREATE INDEX idx_users_email ON users(EMAIL);
CREATE INDEX idx_users_status ON users(STATUS);

-- 4. Insert sample data
INSERT INTO users (NAME, EMAIL, PHONE, STATUS) VALUES ('John Doe', 'john.doe@example.com', '+1234567890', 'active');
INSERT INTO users (NAME, EMAIL, PHONE, STATUS) VALUES ('Jane Smith', 'jane.smith@example.com', '+0987654321', 'active');
INSERT INTO users (NAME, EMAIL, PHONE, STATUS) VALUES ('Bob Johnson', 'bob.johnson@example.com', '+1122334455', 'active');

-- 5. Commit changes
COMMIT;

-- 6. Verify setup
SELECT 'Table created successfully in SCOTT schema' as status FROM dual;
SELECT COUNT(*) as user_count FROM users;
SELECT * FROM users;

-- 7. Show table information
SELECT table_name, tablespace_name FROM user_tables WHERE table_name = 'USERS';